language: node_js

node_js:
  - "7"

addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always